---
- name: install  & config prometheus
  hosts: my-vm1
 # vars:
  vars_files: 
   - secrets.yml
  become: true
  tasks: 
      
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install prometheus
      ansible.builtin.apt:
        name: prometheus
        state: present

        